name: Test
 
on:
  workflow_dispatch:
  push:
    branches:
      - "*.*.*"
      - "main"
  pull_request:
    branches:
      - "*"
 
permissions:
  contents: read
 
jobs:
  test:
    name: Test Changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
 
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
 
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
 
      - name: Install dependencies & Test with Coverage
        run: mvn clean verify
 
      - name: Archive Jacoco HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/
 
      - name: Coveralls GitHub Action
        # Only works if public and enabled in Coveralls, no token required
        uses: coverallsapp/github-action@v2
        if: always()
        with:
          # This will detect and push `target/site/jacoco/jacoco.xml` if present
          github-token: ${{ secrets.GITHUB_TOKEN }}